---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-config-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-config-example
  template:
    metadata:
      labels:
        app: nginx-config-example
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        env:
        - name: CONFIG_HASH
          value: ${CONFIG_HASH}
        ports:
        - name: frontend
          protocol: TCP
          containerPort: 8080
        - name: admin
          protocol: TCP
          containerPort: 8081
        volumeMounts:
        - name: nginx-config-example-configmap
          mountPath: /etc/nginx/conf.d
        - name: nginx-config-example-secret
          mountPath: /etc/nginx/protected
      volumes:
      - name: nginx-config-example-configmap
        configMap:
          name: nginx-config-example-configmap
      - name: nginx-config-example-secret
        secret:
          secretName: nginx-config-example-secret

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-config-example-frontend
spec:
  type: NodePort
  selector:
    app: nginx-config-example
  ports:
  - name: http
    protocol: TCP
    targetPort: frontend
    port: 80
    nodePort: 31228

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-config-example-admin
spec:
  type: NodePort
  selector:
    app: nginx-config-example
  ports:
  - name: http
    protocol: TCP
    targetPort: admin
    port: 80
    nodePort: 31229
